### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by daniellga** [yutannihilation/savvy#100]
Hi! I was messing around with your crate a bit and have some questions about it.

1. Shouldn't all SEXP structures be marked with `#[repr(transparent)]` or `#[repr(C)]` since SEXP come from C ffi?
2. What's the difference between `self.len` and `self.len()` for `OwnedIntegerSexp`?
3. What's the point of the `raw` field of `OwnedIntegerSexp`?

**Comment by yutannihilation** [comment]
Thanks for your interests!

> Shouldn't all SEXP structures be marked with `#[repr(transparent)]` or `#[repr(C)]` since SEXP come from C ffi?

No. The only thing passed between R and Rust is `SEXP`, which is `*mut c_void` in savvy. There's no assumption about what data structure is behind the pointer, so we don't need the such considerations. Please correct me if I'm wrong!

> What's the difference between `self.len` and `self.len()` for `OwnedIntegerSexp`?

Same. `len` is a private field, and `len()` is public.

> What's the point of the raw field of OwnedIntegerSexp?

The owned types stores the pointer to the underlying data so that you don't need to call the accessor functions like `INTEGER()` or `INTEGER_ELT()` every time. This is possible because the SEXP created by `Rf_allocVector()` is non-ALTREP, which is not the case if the `SEXP` is supplied from the R session.

**Comment by daniellga** [comment]
Thanks! The only thing I didn't understand is why to keep `len` as a field in this case.

**Comment by yutannihilation** [comment]
Ah, okay. Having `len` is similar to `raw`. You need to call `Rf_xlength()` to know the length of a SEXP. But, in the owned-version's case, the length is already known because it's created either by `new(<length>)` or `from(&[T])`.
