### ISSUE TITLE
Feature Request: `savvy-cli build --for-cran`

### ISSUE THREAD

**Issue by t-kalinowski** [yutannihilation/savvy#286]
It would be helpful to have a command in `savvy-cli` that simplifies the process of preparing an R source package for CRAN. Currently, getting a `savvy`-using package ready for CRAN involves additional steps like vendoring Rust dependencies, updating Makevars, configuring cargo settings, and generating an authors file.

A `build --for-cran` command could help by automating these extra steps while keeping the standard package development process with `savvy` straightforward.

**Comment by yutannihilation** [comment]
In general, I'm strongly against encouraging innocent users to submit their Rust-powered package to CRAN, which leads them to a lot of troubles. To be clear, it's totally possible to use Rust in CRAN packages, but I believe it's expert-only. For example, typical problems they face are

* the size of the vendored source code is too huge
* it cannot be compiled with a bit older version of Rust toolchain installed in the CRAN machines (currently, 1.69)

Both cannot be automatically fixed by such a command. So, it's inappropriate to advertise "CRAN-ready".

That said, I'm curious why you wanted this feature. If you want to vendor the source on building the package, prqlr's setup might help.

https://github.com/PRQL/prqlc-r

**Comment by yutannihilation** [comment]
Closing this for now. Please let me know if you need some specific feature to get your package on CRAN!

**Comment by t-kalinowski** [comment]
Thanks! Sorry for not getting back to you sooner. I will need this eventually and will be happy to work on it when that time comes.
